# Site settings
title: Shantanu Kumar
email: kumarshantanu95@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sourkream.github.io" # the base hostname & protocol for your site
twitter_username: ThatGuyFrmDelhi
instagram_username: ThatGuyFromDelhi
github_username:  SourKream

# Build settings
markdown: kramdown
