# Site settings
title: Shantanu Kumar
email: kumarshantanu95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a BTech student at IIT Delhi. I am building this webpage for my profile and my projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sourkream.github.io" # the base hostname & protocol for your site
#twitter_username: ShantanuKumar95
github_username:  SourKream

# Build settings
markdown: kramdown
